// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ibc/applications/transfer/v1/tx.proto

package ibc.applications.transfer.v1;

public final class Tx {
  private Tx() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MsgTransferOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ibc.applications.transfer.v1.MsgTransfer)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * the port on which the packet will be sent
     * </pre>
     *
     * <code>string source_port = 1 [(.gogoproto.moretags) = "yaml:&#92;"source_port&#92;""];</code>
     * @return The sourcePort.
     */
    java.lang.String getSourcePort();
    /**
     * <pre>
     * the port on which the packet will be sent
     * </pre>
     *
     * <code>string source_port = 1 [(.gogoproto.moretags) = "yaml:&#92;"source_port&#92;""];</code>
     * @return The bytes for sourcePort.
     */
    com.google.protobuf.ByteString
        getSourcePortBytes();

    /**
     * <pre>
     * the channel by which the packet will be sent
     * </pre>
     *
     * <code>string source_channel = 2 [(.gogoproto.moretags) = "yaml:&#92;"source_channel&#92;""];</code>
     * @return The sourceChannel.
     */
    java.lang.String getSourceChannel();
    /**
     * <pre>
     * the channel by which the packet will be sent
     * </pre>
     *
     * <code>string source_channel = 2 [(.gogoproto.moretags) = "yaml:&#92;"source_channel&#92;""];</code>
     * @return The bytes for sourceChannel.
     */
    com.google.protobuf.ByteString
        getSourceChannelBytes();

    /**
     * <pre>
     * the tokens to be transferred
     * </pre>
     *
     * <code>.cosmos.base.v1beta1.Coin token = 3 [(.gogoproto.nullable) = false];</code>
     * @return Whether the token field is set.
     */
    boolean hasToken();
    /**
     * <pre>
     * the tokens to be transferred
     * </pre>
     *
     * <code>.cosmos.base.v1beta1.Coin token = 3 [(.gogoproto.nullable) = false];</code>
     * @return The token.
     */
    cosmos.base.v1beta1.CoinOuterClass.Coin getToken();
    /**
     * <pre>
     * the tokens to be transferred
     * </pre>
     *
     * <code>.cosmos.base.v1beta1.Coin token = 3 [(.gogoproto.nullable) = false];</code>
     */
    cosmos.base.v1beta1.CoinOuterClass.CoinOrBuilder getTokenOrBuilder();

    /**
     * <pre>
     * the sender address
     * </pre>
     *
     * <code>string sender = 4;</code>
     * @return The sender.
     */
    java.lang.String getSender();
    /**
     * <pre>
     * the sender address
     * </pre>
     *
     * <code>string sender = 4;</code>
     * @return The bytes for sender.
     */
    com.google.protobuf.ByteString
        getSenderBytes();

    /**
     * <pre>
     * the recipient address on the destination chain
     * </pre>
     *
     * <code>string receiver = 5;</code>
     * @return The receiver.
     */
    java.lang.String getReceiver();
    /**
     * <pre>
     * the recipient address on the destination chain
     * </pre>
     *
     * <code>string receiver = 5;</code>
     * @return The bytes for receiver.
     */
    com.google.protobuf.ByteString
        getReceiverBytes();

    /**
     * <pre>
     * Timeout height relative to the current block height.
     * The timeout is disabled when set to 0.
     * </pre>
     *
     * <code>.ibc.core.client.v1.Height timeout_height = 6 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"timeout_height&#92;""];</code>
     * @return Whether the timeoutHeight field is set.
     */
    boolean hasTimeoutHeight();
    /**
     * <pre>
     * Timeout height relative to the current block height.
     * The timeout is disabled when set to 0.
     * </pre>
     *
     * <code>.ibc.core.client.v1.Height timeout_height = 6 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"timeout_height&#92;""];</code>
     * @return The timeoutHeight.
     */
    ibc.core.client.v1.Client.Height getTimeoutHeight();
    /**
     * <pre>
     * Timeout height relative to the current block height.
     * The timeout is disabled when set to 0.
     * </pre>
     *
     * <code>.ibc.core.client.v1.Height timeout_height = 6 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"timeout_height&#92;""];</code>
     */
    ibc.core.client.v1.Client.HeightOrBuilder getTimeoutHeightOrBuilder();

    /**
     * <pre>
     * Timeout timestamp (in nanoseconds) relative to the current block timestamp.
     * The timeout is disabled when set to 0.
     * </pre>
     *
     * <code>uint64 timeout_timestamp = 7 [(.gogoproto.moretags) = "yaml:&#92;"timeout_timestamp&#92;""];</code>
     * @return The timeoutTimestamp.
     */
    long getTimeoutTimestamp();
  }
  /**
   * <pre>
   * MsgTransfer defines a msg to transfer fungible tokens (i.e Coins) between
   * ICS20 enabled chains. See ICS Spec here:
   * https://github.com/cosmos/ics/tree/master/spec/ics-020-fungible-token-transfer#data-structures
   * </pre>
   *
   * Protobuf type {@code ibc.applications.transfer.v1.MsgTransfer}
   */
  public static final class MsgTransfer extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ibc.applications.transfer.v1.MsgTransfer)
      MsgTransferOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MsgTransfer.newBuilder() to construct.
    private MsgTransfer(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MsgTransfer() {
      sourcePort_ = "";
      sourceChannel_ = "";
      sender_ = "";
      receiver_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MsgTransfer();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ibc.applications.transfer.v1.Tx.internal_static_ibc_applications_transfer_v1_MsgTransfer_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ibc.applications.transfer.v1.Tx.internal_static_ibc_applications_transfer_v1_MsgTransfer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ibc.applications.transfer.v1.Tx.MsgTransfer.class, ibc.applications.transfer.v1.Tx.MsgTransfer.Builder.class);
    }

    public static final int SOURCE_PORT_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object sourcePort_ = "";
    /**
     * <pre>
     * the port on which the packet will be sent
     * </pre>
     *
     * <code>string source_port = 1 [(.gogoproto.moretags) = "yaml:&#92;"source_port&#92;""];</code>
     * @return The sourcePort.
     */
    @java.lang.Override
    public java.lang.String getSourcePort() {
      java.lang.Object ref = sourcePort_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sourcePort_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * the port on which the packet will be sent
     * </pre>
     *
     * <code>string source_port = 1 [(.gogoproto.moretags) = "yaml:&#92;"source_port&#92;""];</code>
     * @return The bytes for sourcePort.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSourcePortBytes() {
      java.lang.Object ref = sourcePort_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sourcePort_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SOURCE_CHANNEL_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object sourceChannel_ = "";
    /**
     * <pre>
     * the channel by which the packet will be sent
     * </pre>
     *
     * <code>string source_channel = 2 [(.gogoproto.moretags) = "yaml:&#92;"source_channel&#92;""];</code>
     * @return The sourceChannel.
     */
    @java.lang.Override
    public java.lang.String getSourceChannel() {
      java.lang.Object ref = sourceChannel_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sourceChannel_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * the channel by which the packet will be sent
     * </pre>
     *
     * <code>string source_channel = 2 [(.gogoproto.moretags) = "yaml:&#92;"source_channel&#92;""];</code>
     * @return The bytes for sourceChannel.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSourceChannelBytes() {
      java.lang.Object ref = sourceChannel_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sourceChannel_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TOKEN_FIELD_NUMBER = 3;
    private cosmos.base.v1beta1.CoinOuterClass.Coin token_;
    /**
     * <pre>
     * the tokens to be transferred
     * </pre>
     *
     * <code>.cosmos.base.v1beta1.Coin token = 3 [(.gogoproto.nullable) = false];</code>
     * @return Whether the token field is set.
     */
    @java.lang.Override
    public boolean hasToken() {
      return token_ != null;
    }
    /**
     * <pre>
     * the tokens to be transferred
     * </pre>
     *
     * <code>.cosmos.base.v1beta1.Coin token = 3 [(.gogoproto.nullable) = false];</code>
     * @return The token.
     */
    @java.lang.Override
    public cosmos.base.v1beta1.CoinOuterClass.Coin getToken() {
      return token_ == null ? cosmos.base.v1beta1.CoinOuterClass.Coin.getDefaultInstance() : token_;
    }
    /**
     * <pre>
     * the tokens to be transferred
     * </pre>
     *
     * <code>.cosmos.base.v1beta1.Coin token = 3 [(.gogoproto.nullable) = false];</code>
     */
    @java.lang.Override
    public cosmos.base.v1beta1.CoinOuterClass.CoinOrBuilder getTokenOrBuilder() {
      return token_ == null ? cosmos.base.v1beta1.CoinOuterClass.Coin.getDefaultInstance() : token_;
    }

    public static final int SENDER_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object sender_ = "";
    /**
     * <pre>
     * the sender address
     * </pre>
     *
     * <code>string sender = 4;</code>
     * @return The sender.
     */
    @java.lang.Override
    public java.lang.String getSender() {
      java.lang.Object ref = sender_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sender_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * the sender address
     * </pre>
     *
     * <code>string sender = 4;</code>
     * @return The bytes for sender.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSenderBytes() {
      java.lang.Object ref = sender_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sender_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RECEIVER_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private volatile java.lang.Object receiver_ = "";
    /**
     * <pre>
     * the recipient address on the destination chain
     * </pre>
     *
     * <code>string receiver = 5;</code>
     * @return The receiver.
     */
    @java.lang.Override
    public java.lang.String getReceiver() {
      java.lang.Object ref = receiver_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        receiver_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * the recipient address on the destination chain
     * </pre>
     *
     * <code>string receiver = 5;</code>
     * @return The bytes for receiver.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getReceiverBytes() {
      java.lang.Object ref = receiver_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        receiver_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIMEOUT_HEIGHT_FIELD_NUMBER = 6;
    private ibc.core.client.v1.Client.Height timeoutHeight_;
    /**
     * <pre>
     * Timeout height relative to the current block height.
     * The timeout is disabled when set to 0.
     * </pre>
     *
     * <code>.ibc.core.client.v1.Height timeout_height = 6 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"timeout_height&#92;""];</code>
     * @return Whether the timeoutHeight field is set.
     */
    @java.lang.Override
    public boolean hasTimeoutHeight() {
      return timeoutHeight_ != null;
    }
    /**
     * <pre>
     * Timeout height relative to the current block height.
     * The timeout is disabled when set to 0.
     * </pre>
     *
     * <code>.ibc.core.client.v1.Height timeout_height = 6 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"timeout_height&#92;""];</code>
     * @return The timeoutHeight.
     */
    @java.lang.Override
    public ibc.core.client.v1.Client.Height getTimeoutHeight() {
      return timeoutHeight_ == null ? ibc.core.client.v1.Client.Height.getDefaultInstance() : timeoutHeight_;
    }
    /**
     * <pre>
     * Timeout height relative to the current block height.
     * The timeout is disabled when set to 0.
     * </pre>
     *
     * <code>.ibc.core.client.v1.Height timeout_height = 6 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"timeout_height&#92;""];</code>
     */
    @java.lang.Override
    public ibc.core.client.v1.Client.HeightOrBuilder getTimeoutHeightOrBuilder() {
      return timeoutHeight_ == null ? ibc.core.client.v1.Client.Height.getDefaultInstance() : timeoutHeight_;
    }

    public static final int TIMEOUT_TIMESTAMP_FIELD_NUMBER = 7;
    private long timeoutTimestamp_ = 0L;
    /**
     * <pre>
     * Timeout timestamp (in nanoseconds) relative to the current block timestamp.
     * The timeout is disabled when set to 0.
     * </pre>
     *
     * <code>uint64 timeout_timestamp = 7 [(.gogoproto.moretags) = "yaml:&#92;"timeout_timestamp&#92;""];</code>
     * @return The timeoutTimestamp.
     */
    @java.lang.Override
    public long getTimeoutTimestamp() {
      return timeoutTimestamp_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sourcePort_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, sourcePort_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sourceChannel_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, sourceChannel_);
      }
      if (token_ != null) {
        output.writeMessage(3, getToken());
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sender_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, sender_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(receiver_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, receiver_);
      }
      if (timeoutHeight_ != null) {
        output.writeMessage(6, getTimeoutHeight());
      }
      if (timeoutTimestamp_ != 0L) {
        output.writeUInt64(7, timeoutTimestamp_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sourcePort_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, sourcePort_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sourceChannel_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, sourceChannel_);
      }
      if (token_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getToken());
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sender_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, sender_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(receiver_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, receiver_);
      }
      if (timeoutHeight_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, getTimeoutHeight());
      }
      if (timeoutTimestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(7, timeoutTimestamp_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ibc.applications.transfer.v1.Tx.MsgTransfer)) {
        return super.equals(obj);
      }
      ibc.applications.transfer.v1.Tx.MsgTransfer other = (ibc.applications.transfer.v1.Tx.MsgTransfer) obj;

      if (!getSourcePort()
          .equals(other.getSourcePort())) return false;
      if (!getSourceChannel()
          .equals(other.getSourceChannel())) return false;
      if (hasToken() != other.hasToken()) return false;
      if (hasToken()) {
        if (!getToken()
            .equals(other.getToken())) return false;
      }
      if (!getSender()
          .equals(other.getSender())) return false;
      if (!getReceiver()
          .equals(other.getReceiver())) return false;
      if (hasTimeoutHeight() != other.hasTimeoutHeight()) return false;
      if (hasTimeoutHeight()) {
        if (!getTimeoutHeight()
            .equals(other.getTimeoutHeight())) return false;
      }
      if (getTimeoutTimestamp()
          != other.getTimeoutTimestamp()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SOURCE_PORT_FIELD_NUMBER;
      hash = (53 * hash) + getSourcePort().hashCode();
      hash = (37 * hash) + SOURCE_CHANNEL_FIELD_NUMBER;
      hash = (53 * hash) + getSourceChannel().hashCode();
      if (hasToken()) {
        hash = (37 * hash) + TOKEN_FIELD_NUMBER;
        hash = (53 * hash) + getToken().hashCode();
      }
      hash = (37 * hash) + SENDER_FIELD_NUMBER;
      hash = (53 * hash) + getSender().hashCode();
      hash = (37 * hash) + RECEIVER_FIELD_NUMBER;
      hash = (53 * hash) + getReceiver().hashCode();
      if (hasTimeoutHeight()) {
        hash = (37 * hash) + TIMEOUT_HEIGHT_FIELD_NUMBER;
        hash = (53 * hash) + getTimeoutHeight().hashCode();
      }
      hash = (37 * hash) + TIMEOUT_TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimeoutTimestamp());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ibc.applications.transfer.v1.Tx.MsgTransfer parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ibc.applications.transfer.v1.Tx.MsgTransfer parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ibc.applications.transfer.v1.Tx.MsgTransfer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ibc.applications.transfer.v1.Tx.MsgTransfer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ibc.applications.transfer.v1.Tx.MsgTransfer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ibc.applications.transfer.v1.Tx.MsgTransfer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ibc.applications.transfer.v1.Tx.MsgTransfer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ibc.applications.transfer.v1.Tx.MsgTransfer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ibc.applications.transfer.v1.Tx.MsgTransfer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ibc.applications.transfer.v1.Tx.MsgTransfer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ibc.applications.transfer.v1.Tx.MsgTransfer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ibc.applications.transfer.v1.Tx.MsgTransfer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ibc.applications.transfer.v1.Tx.MsgTransfer prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * MsgTransfer defines a msg to transfer fungible tokens (i.e Coins) between
     * ICS20 enabled chains. See ICS Spec here:
     * https://github.com/cosmos/ics/tree/master/spec/ics-020-fungible-token-transfer#data-structures
     * </pre>
     *
     * Protobuf type {@code ibc.applications.transfer.v1.MsgTransfer}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ibc.applications.transfer.v1.MsgTransfer)
        ibc.applications.transfer.v1.Tx.MsgTransferOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ibc.applications.transfer.v1.Tx.internal_static_ibc_applications_transfer_v1_MsgTransfer_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ibc.applications.transfer.v1.Tx.internal_static_ibc_applications_transfer_v1_MsgTransfer_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ibc.applications.transfer.v1.Tx.MsgTransfer.class, ibc.applications.transfer.v1.Tx.MsgTransfer.Builder.class);
      }

      // Construct using ibc.applications.transfer.v1.Tx.MsgTransfer.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        sourcePort_ = "";
        sourceChannel_ = "";
        token_ = null;
        if (tokenBuilder_ != null) {
          tokenBuilder_.dispose();
          tokenBuilder_ = null;
        }
        sender_ = "";
        receiver_ = "";
        timeoutHeight_ = null;
        if (timeoutHeightBuilder_ != null) {
          timeoutHeightBuilder_.dispose();
          timeoutHeightBuilder_ = null;
        }
        timeoutTimestamp_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ibc.applications.transfer.v1.Tx.internal_static_ibc_applications_transfer_v1_MsgTransfer_descriptor;
      }

      @java.lang.Override
      public ibc.applications.transfer.v1.Tx.MsgTransfer getDefaultInstanceForType() {
        return ibc.applications.transfer.v1.Tx.MsgTransfer.getDefaultInstance();
      }

      @java.lang.Override
      public ibc.applications.transfer.v1.Tx.MsgTransfer build() {
        ibc.applications.transfer.v1.Tx.MsgTransfer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ibc.applications.transfer.v1.Tx.MsgTransfer buildPartial() {
        ibc.applications.transfer.v1.Tx.MsgTransfer result = new ibc.applications.transfer.v1.Tx.MsgTransfer(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(ibc.applications.transfer.v1.Tx.MsgTransfer result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.sourcePort_ = sourcePort_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.sourceChannel_ = sourceChannel_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.token_ = tokenBuilder_ == null
              ? token_
              : tokenBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.sender_ = sender_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.receiver_ = receiver_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.timeoutHeight_ = timeoutHeightBuilder_ == null
              ? timeoutHeight_
              : timeoutHeightBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.timeoutTimestamp_ = timeoutTimestamp_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ibc.applications.transfer.v1.Tx.MsgTransfer) {
          return mergeFrom((ibc.applications.transfer.v1.Tx.MsgTransfer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ibc.applications.transfer.v1.Tx.MsgTransfer other) {
        if (other == ibc.applications.transfer.v1.Tx.MsgTransfer.getDefaultInstance()) return this;
        if (!other.getSourcePort().isEmpty()) {
          sourcePort_ = other.sourcePort_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getSourceChannel().isEmpty()) {
          sourceChannel_ = other.sourceChannel_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.hasToken()) {
          mergeToken(other.getToken());
        }
        if (!other.getSender().isEmpty()) {
          sender_ = other.sender_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (!other.getReceiver().isEmpty()) {
          receiver_ = other.receiver_;
          bitField0_ |= 0x00000010;
          onChanged();
        }
        if (other.hasTimeoutHeight()) {
          mergeTimeoutHeight(other.getTimeoutHeight());
        }
        if (other.getTimeoutTimestamp() != 0L) {
          setTimeoutTimestamp(other.getTimeoutTimestamp());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                sourcePort_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                sourceChannel_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                input.readMessage(
                    getTokenFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                sender_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 42: {
                receiver_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              case 50: {
                input.readMessage(
                    getTimeoutHeightFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000020;
                break;
              } // case 50
              case 56: {
                timeoutTimestamp_ = input.readUInt64();
                bitField0_ |= 0x00000040;
                break;
              } // case 56
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object sourcePort_ = "";
      /**
       * <pre>
       * the port on which the packet will be sent
       * </pre>
       *
       * <code>string source_port = 1 [(.gogoproto.moretags) = "yaml:&#92;"source_port&#92;""];</code>
       * @return The sourcePort.
       */
      public java.lang.String getSourcePort() {
        java.lang.Object ref = sourcePort_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sourcePort_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * the port on which the packet will be sent
       * </pre>
       *
       * <code>string source_port = 1 [(.gogoproto.moretags) = "yaml:&#92;"source_port&#92;""];</code>
       * @return The bytes for sourcePort.
       */
      public com.google.protobuf.ByteString
          getSourcePortBytes() {
        java.lang.Object ref = sourcePort_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sourcePort_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * the port on which the packet will be sent
       * </pre>
       *
       * <code>string source_port = 1 [(.gogoproto.moretags) = "yaml:&#92;"source_port&#92;""];</code>
       * @param value The sourcePort to set.
       * @return This builder for chaining.
       */
      public Builder setSourcePort(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        sourcePort_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * the port on which the packet will be sent
       * </pre>
       *
       * <code>string source_port = 1 [(.gogoproto.moretags) = "yaml:&#92;"source_port&#92;""];</code>
       * @return This builder for chaining.
       */
      public Builder clearSourcePort() {
        sourcePort_ = getDefaultInstance().getSourcePort();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * the port on which the packet will be sent
       * </pre>
       *
       * <code>string source_port = 1 [(.gogoproto.moretags) = "yaml:&#92;"source_port&#92;""];</code>
       * @param value The bytes for sourcePort to set.
       * @return This builder for chaining.
       */
      public Builder setSourcePortBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        sourcePort_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object sourceChannel_ = "";
      /**
       * <pre>
       * the channel by which the packet will be sent
       * </pre>
       *
       * <code>string source_channel = 2 [(.gogoproto.moretags) = "yaml:&#92;"source_channel&#92;""];</code>
       * @return The sourceChannel.
       */
      public java.lang.String getSourceChannel() {
        java.lang.Object ref = sourceChannel_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sourceChannel_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * the channel by which the packet will be sent
       * </pre>
       *
       * <code>string source_channel = 2 [(.gogoproto.moretags) = "yaml:&#92;"source_channel&#92;""];</code>
       * @return The bytes for sourceChannel.
       */
      public com.google.protobuf.ByteString
          getSourceChannelBytes() {
        java.lang.Object ref = sourceChannel_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sourceChannel_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * the channel by which the packet will be sent
       * </pre>
       *
       * <code>string source_channel = 2 [(.gogoproto.moretags) = "yaml:&#92;"source_channel&#92;""];</code>
       * @param value The sourceChannel to set.
       * @return This builder for chaining.
       */
      public Builder setSourceChannel(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        sourceChannel_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * the channel by which the packet will be sent
       * </pre>
       *
       * <code>string source_channel = 2 [(.gogoproto.moretags) = "yaml:&#92;"source_channel&#92;""];</code>
       * @return This builder for chaining.
       */
      public Builder clearSourceChannel() {
        sourceChannel_ = getDefaultInstance().getSourceChannel();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * the channel by which the packet will be sent
       * </pre>
       *
       * <code>string source_channel = 2 [(.gogoproto.moretags) = "yaml:&#92;"source_channel&#92;""];</code>
       * @param value The bytes for sourceChannel to set.
       * @return This builder for chaining.
       */
      public Builder setSourceChannelBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        sourceChannel_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private cosmos.base.v1beta1.CoinOuterClass.Coin token_;
      private com.google.protobuf.SingleFieldBuilderV3<
          cosmos.base.v1beta1.CoinOuterClass.Coin, cosmos.base.v1beta1.CoinOuterClass.Coin.Builder, cosmos.base.v1beta1.CoinOuterClass.CoinOrBuilder> tokenBuilder_;
      /**
       * <pre>
       * the tokens to be transferred
       * </pre>
       *
       * <code>.cosmos.base.v1beta1.Coin token = 3 [(.gogoproto.nullable) = false];</code>
       * @return Whether the token field is set.
       */
      public boolean hasToken() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <pre>
       * the tokens to be transferred
       * </pre>
       *
       * <code>.cosmos.base.v1beta1.Coin token = 3 [(.gogoproto.nullable) = false];</code>
       * @return The token.
       */
      public cosmos.base.v1beta1.CoinOuterClass.Coin getToken() {
        if (tokenBuilder_ == null) {
          return token_ == null ? cosmos.base.v1beta1.CoinOuterClass.Coin.getDefaultInstance() : token_;
        } else {
          return tokenBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * the tokens to be transferred
       * </pre>
       *
       * <code>.cosmos.base.v1beta1.Coin token = 3 [(.gogoproto.nullable) = false];</code>
       */
      public Builder setToken(cosmos.base.v1beta1.CoinOuterClass.Coin value) {
        if (tokenBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          token_ = value;
        } else {
          tokenBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * the tokens to be transferred
       * </pre>
       *
       * <code>.cosmos.base.v1beta1.Coin token = 3 [(.gogoproto.nullable) = false];</code>
       */
      public Builder setToken(
          cosmos.base.v1beta1.CoinOuterClass.Coin.Builder builderForValue) {
        if (tokenBuilder_ == null) {
          token_ = builderForValue.build();
        } else {
          tokenBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * the tokens to be transferred
       * </pre>
       *
       * <code>.cosmos.base.v1beta1.Coin token = 3 [(.gogoproto.nullable) = false];</code>
       */
      public Builder mergeToken(cosmos.base.v1beta1.CoinOuterClass.Coin value) {
        if (tokenBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0) &&
            token_ != null &&
            token_ != cosmos.base.v1beta1.CoinOuterClass.Coin.getDefaultInstance()) {
            getTokenBuilder().mergeFrom(value);
          } else {
            token_ = value;
          }
        } else {
          tokenBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * the tokens to be transferred
       * </pre>
       *
       * <code>.cosmos.base.v1beta1.Coin token = 3 [(.gogoproto.nullable) = false];</code>
       */
      public Builder clearToken() {
        bitField0_ = (bitField0_ & ~0x00000004);
        token_ = null;
        if (tokenBuilder_ != null) {
          tokenBuilder_.dispose();
          tokenBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <pre>
       * the tokens to be transferred
       * </pre>
       *
       * <code>.cosmos.base.v1beta1.Coin token = 3 [(.gogoproto.nullable) = false];</code>
       */
      public cosmos.base.v1beta1.CoinOuterClass.Coin.Builder getTokenBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getTokenFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * the tokens to be transferred
       * </pre>
       *
       * <code>.cosmos.base.v1beta1.Coin token = 3 [(.gogoproto.nullable) = false];</code>
       */
      public cosmos.base.v1beta1.CoinOuterClass.CoinOrBuilder getTokenOrBuilder() {
        if (tokenBuilder_ != null) {
          return tokenBuilder_.getMessageOrBuilder();
        } else {
          return token_ == null ?
              cosmos.base.v1beta1.CoinOuterClass.Coin.getDefaultInstance() : token_;
        }
      }
      /**
       * <pre>
       * the tokens to be transferred
       * </pre>
       *
       * <code>.cosmos.base.v1beta1.Coin token = 3 [(.gogoproto.nullable) = false];</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          cosmos.base.v1beta1.CoinOuterClass.Coin, cosmos.base.v1beta1.CoinOuterClass.Coin.Builder, cosmos.base.v1beta1.CoinOuterClass.CoinOrBuilder> 
          getTokenFieldBuilder() {
        if (tokenBuilder_ == null) {
          tokenBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              cosmos.base.v1beta1.CoinOuterClass.Coin, cosmos.base.v1beta1.CoinOuterClass.Coin.Builder, cosmos.base.v1beta1.CoinOuterClass.CoinOrBuilder>(
                  getToken(),
                  getParentForChildren(),
                  isClean());
          token_ = null;
        }
        return tokenBuilder_;
      }

      private java.lang.Object sender_ = "";
      /**
       * <pre>
       * the sender address
       * </pre>
       *
       * <code>string sender = 4;</code>
       * @return The sender.
       */
      public java.lang.String getSender() {
        java.lang.Object ref = sender_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sender_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * the sender address
       * </pre>
       *
       * <code>string sender = 4;</code>
       * @return The bytes for sender.
       */
      public com.google.protobuf.ByteString
          getSenderBytes() {
        java.lang.Object ref = sender_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sender_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * the sender address
       * </pre>
       *
       * <code>string sender = 4;</code>
       * @param value The sender to set.
       * @return This builder for chaining.
       */
      public Builder setSender(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        sender_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * the sender address
       * </pre>
       *
       * <code>string sender = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearSender() {
        sender_ = getDefaultInstance().getSender();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * the sender address
       * </pre>
       *
       * <code>string sender = 4;</code>
       * @param value The bytes for sender to set.
       * @return This builder for chaining.
       */
      public Builder setSenderBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        sender_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private java.lang.Object receiver_ = "";
      /**
       * <pre>
       * the recipient address on the destination chain
       * </pre>
       *
       * <code>string receiver = 5;</code>
       * @return The receiver.
       */
      public java.lang.String getReceiver() {
        java.lang.Object ref = receiver_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          receiver_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * the recipient address on the destination chain
       * </pre>
       *
       * <code>string receiver = 5;</code>
       * @return The bytes for receiver.
       */
      public com.google.protobuf.ByteString
          getReceiverBytes() {
        java.lang.Object ref = receiver_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          receiver_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * the recipient address on the destination chain
       * </pre>
       *
       * <code>string receiver = 5;</code>
       * @param value The receiver to set.
       * @return This builder for chaining.
       */
      public Builder setReceiver(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        receiver_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * the recipient address on the destination chain
       * </pre>
       *
       * <code>string receiver = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearReceiver() {
        receiver_ = getDefaultInstance().getReceiver();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * the recipient address on the destination chain
       * </pre>
       *
       * <code>string receiver = 5;</code>
       * @param value The bytes for receiver to set.
       * @return This builder for chaining.
       */
      public Builder setReceiverBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        receiver_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }

      private ibc.core.client.v1.Client.Height timeoutHeight_;
      private com.google.protobuf.SingleFieldBuilderV3<
          ibc.core.client.v1.Client.Height, ibc.core.client.v1.Client.Height.Builder, ibc.core.client.v1.Client.HeightOrBuilder> timeoutHeightBuilder_;
      /**
       * <pre>
       * Timeout height relative to the current block height.
       * The timeout is disabled when set to 0.
       * </pre>
       *
       * <code>.ibc.core.client.v1.Height timeout_height = 6 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"timeout_height&#92;""];</code>
       * @return Whether the timeoutHeight field is set.
       */
      public boolean hasTimeoutHeight() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <pre>
       * Timeout height relative to the current block height.
       * The timeout is disabled when set to 0.
       * </pre>
       *
       * <code>.ibc.core.client.v1.Height timeout_height = 6 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"timeout_height&#92;""];</code>
       * @return The timeoutHeight.
       */
      public ibc.core.client.v1.Client.Height getTimeoutHeight() {
        if (timeoutHeightBuilder_ == null) {
          return timeoutHeight_ == null ? ibc.core.client.v1.Client.Height.getDefaultInstance() : timeoutHeight_;
        } else {
          return timeoutHeightBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * Timeout height relative to the current block height.
       * The timeout is disabled when set to 0.
       * </pre>
       *
       * <code>.ibc.core.client.v1.Height timeout_height = 6 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"timeout_height&#92;""];</code>
       */
      public Builder setTimeoutHeight(ibc.core.client.v1.Client.Height value) {
        if (timeoutHeightBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          timeoutHeight_ = value;
        } else {
          timeoutHeightBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Timeout height relative to the current block height.
       * The timeout is disabled when set to 0.
       * </pre>
       *
       * <code>.ibc.core.client.v1.Height timeout_height = 6 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"timeout_height&#92;""];</code>
       */
      public Builder setTimeoutHeight(
          ibc.core.client.v1.Client.Height.Builder builderForValue) {
        if (timeoutHeightBuilder_ == null) {
          timeoutHeight_ = builderForValue.build();
        } else {
          timeoutHeightBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Timeout height relative to the current block height.
       * The timeout is disabled when set to 0.
       * </pre>
       *
       * <code>.ibc.core.client.v1.Height timeout_height = 6 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"timeout_height&#92;""];</code>
       */
      public Builder mergeTimeoutHeight(ibc.core.client.v1.Client.Height value) {
        if (timeoutHeightBuilder_ == null) {
          if (((bitField0_ & 0x00000020) != 0) &&
            timeoutHeight_ != null &&
            timeoutHeight_ != ibc.core.client.v1.Client.Height.getDefaultInstance()) {
            getTimeoutHeightBuilder().mergeFrom(value);
          } else {
            timeoutHeight_ = value;
          }
        } else {
          timeoutHeightBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Timeout height relative to the current block height.
       * The timeout is disabled when set to 0.
       * </pre>
       *
       * <code>.ibc.core.client.v1.Height timeout_height = 6 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"timeout_height&#92;""];</code>
       */
      public Builder clearTimeoutHeight() {
        bitField0_ = (bitField0_ & ~0x00000020);
        timeoutHeight_ = null;
        if (timeoutHeightBuilder_ != null) {
          timeoutHeightBuilder_.dispose();
          timeoutHeightBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Timeout height relative to the current block height.
       * The timeout is disabled when set to 0.
       * </pre>
       *
       * <code>.ibc.core.client.v1.Height timeout_height = 6 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"timeout_height&#92;""];</code>
       */
      public ibc.core.client.v1.Client.Height.Builder getTimeoutHeightBuilder() {
        bitField0_ |= 0x00000020;
        onChanged();
        return getTimeoutHeightFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * Timeout height relative to the current block height.
       * The timeout is disabled when set to 0.
       * </pre>
       *
       * <code>.ibc.core.client.v1.Height timeout_height = 6 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"timeout_height&#92;""];</code>
       */
      public ibc.core.client.v1.Client.HeightOrBuilder getTimeoutHeightOrBuilder() {
        if (timeoutHeightBuilder_ != null) {
          return timeoutHeightBuilder_.getMessageOrBuilder();
        } else {
          return timeoutHeight_ == null ?
              ibc.core.client.v1.Client.Height.getDefaultInstance() : timeoutHeight_;
        }
      }
      /**
       * <pre>
       * Timeout height relative to the current block height.
       * The timeout is disabled when set to 0.
       * </pre>
       *
       * <code>.ibc.core.client.v1.Height timeout_height = 6 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"timeout_height&#92;""];</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          ibc.core.client.v1.Client.Height, ibc.core.client.v1.Client.Height.Builder, ibc.core.client.v1.Client.HeightOrBuilder> 
          getTimeoutHeightFieldBuilder() {
        if (timeoutHeightBuilder_ == null) {
          timeoutHeightBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              ibc.core.client.v1.Client.Height, ibc.core.client.v1.Client.Height.Builder, ibc.core.client.v1.Client.HeightOrBuilder>(
                  getTimeoutHeight(),
                  getParentForChildren(),
                  isClean());
          timeoutHeight_ = null;
        }
        return timeoutHeightBuilder_;
      }

      private long timeoutTimestamp_ ;
      /**
       * <pre>
       * Timeout timestamp (in nanoseconds) relative to the current block timestamp.
       * The timeout is disabled when set to 0.
       * </pre>
       *
       * <code>uint64 timeout_timestamp = 7 [(.gogoproto.moretags) = "yaml:&#92;"timeout_timestamp&#92;""];</code>
       * @return The timeoutTimestamp.
       */
      @java.lang.Override
      public long getTimeoutTimestamp() {
        return timeoutTimestamp_;
      }
      /**
       * <pre>
       * Timeout timestamp (in nanoseconds) relative to the current block timestamp.
       * The timeout is disabled when set to 0.
       * </pre>
       *
       * <code>uint64 timeout_timestamp = 7 [(.gogoproto.moretags) = "yaml:&#92;"timeout_timestamp&#92;""];</code>
       * @param value The timeoutTimestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimeoutTimestamp(long value) {
        
        timeoutTimestamp_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Timeout timestamp (in nanoseconds) relative to the current block timestamp.
       * The timeout is disabled when set to 0.
       * </pre>
       *
       * <code>uint64 timeout_timestamp = 7 [(.gogoproto.moretags) = "yaml:&#92;"timeout_timestamp&#92;""];</code>
       * @return This builder for chaining.
       */
      public Builder clearTimeoutTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000040);
        timeoutTimestamp_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ibc.applications.transfer.v1.MsgTransfer)
    }

    // @@protoc_insertion_point(class_scope:ibc.applications.transfer.v1.MsgTransfer)
    private static final ibc.applications.transfer.v1.Tx.MsgTransfer DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ibc.applications.transfer.v1.Tx.MsgTransfer();
    }

    public static ibc.applications.transfer.v1.Tx.MsgTransfer getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MsgTransfer>
        PARSER = new com.google.protobuf.AbstractParser<MsgTransfer>() {
      @java.lang.Override
      public MsgTransfer parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<MsgTransfer> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MsgTransfer> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ibc.applications.transfer.v1.Tx.MsgTransfer getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MsgTransferResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ibc.applications.transfer.v1.MsgTransferResponse)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * <pre>
   * MsgTransferResponse defines the Msg/Transfer response type.
   * </pre>
   *
   * Protobuf type {@code ibc.applications.transfer.v1.MsgTransferResponse}
   */
  public static final class MsgTransferResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ibc.applications.transfer.v1.MsgTransferResponse)
      MsgTransferResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MsgTransferResponse.newBuilder() to construct.
    private MsgTransferResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MsgTransferResponse() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MsgTransferResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ibc.applications.transfer.v1.Tx.internal_static_ibc_applications_transfer_v1_MsgTransferResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ibc.applications.transfer.v1.Tx.internal_static_ibc_applications_transfer_v1_MsgTransferResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ibc.applications.transfer.v1.Tx.MsgTransferResponse.class, ibc.applications.transfer.v1.Tx.MsgTransferResponse.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ibc.applications.transfer.v1.Tx.MsgTransferResponse)) {
        return super.equals(obj);
      }
      ibc.applications.transfer.v1.Tx.MsgTransferResponse other = (ibc.applications.transfer.v1.Tx.MsgTransferResponse) obj;

      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ibc.applications.transfer.v1.Tx.MsgTransferResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ibc.applications.transfer.v1.Tx.MsgTransferResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ibc.applications.transfer.v1.Tx.MsgTransferResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ibc.applications.transfer.v1.Tx.MsgTransferResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ibc.applications.transfer.v1.Tx.MsgTransferResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ibc.applications.transfer.v1.Tx.MsgTransferResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ibc.applications.transfer.v1.Tx.MsgTransferResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ibc.applications.transfer.v1.Tx.MsgTransferResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ibc.applications.transfer.v1.Tx.MsgTransferResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ibc.applications.transfer.v1.Tx.MsgTransferResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ibc.applications.transfer.v1.Tx.MsgTransferResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ibc.applications.transfer.v1.Tx.MsgTransferResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ibc.applications.transfer.v1.Tx.MsgTransferResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * MsgTransferResponse defines the Msg/Transfer response type.
     * </pre>
     *
     * Protobuf type {@code ibc.applications.transfer.v1.MsgTransferResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ibc.applications.transfer.v1.MsgTransferResponse)
        ibc.applications.transfer.v1.Tx.MsgTransferResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ibc.applications.transfer.v1.Tx.internal_static_ibc_applications_transfer_v1_MsgTransferResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ibc.applications.transfer.v1.Tx.internal_static_ibc_applications_transfer_v1_MsgTransferResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ibc.applications.transfer.v1.Tx.MsgTransferResponse.class, ibc.applications.transfer.v1.Tx.MsgTransferResponse.Builder.class);
      }

      // Construct using ibc.applications.transfer.v1.Tx.MsgTransferResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ibc.applications.transfer.v1.Tx.internal_static_ibc_applications_transfer_v1_MsgTransferResponse_descriptor;
      }

      @java.lang.Override
      public ibc.applications.transfer.v1.Tx.MsgTransferResponse getDefaultInstanceForType() {
        return ibc.applications.transfer.v1.Tx.MsgTransferResponse.getDefaultInstance();
      }

      @java.lang.Override
      public ibc.applications.transfer.v1.Tx.MsgTransferResponse build() {
        ibc.applications.transfer.v1.Tx.MsgTransferResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ibc.applications.transfer.v1.Tx.MsgTransferResponse buildPartial() {
        ibc.applications.transfer.v1.Tx.MsgTransferResponse result = new ibc.applications.transfer.v1.Tx.MsgTransferResponse(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ibc.applications.transfer.v1.Tx.MsgTransferResponse) {
          return mergeFrom((ibc.applications.transfer.v1.Tx.MsgTransferResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ibc.applications.transfer.v1.Tx.MsgTransferResponse other) {
        if (other == ibc.applications.transfer.v1.Tx.MsgTransferResponse.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ibc.applications.transfer.v1.MsgTransferResponse)
    }

    // @@protoc_insertion_point(class_scope:ibc.applications.transfer.v1.MsgTransferResponse)
    private static final ibc.applications.transfer.v1.Tx.MsgTransferResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ibc.applications.transfer.v1.Tx.MsgTransferResponse();
    }

    public static ibc.applications.transfer.v1.Tx.MsgTransferResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MsgTransferResponse>
        PARSER = new com.google.protobuf.AbstractParser<MsgTransferResponse>() {
      @java.lang.Override
      public MsgTransferResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<MsgTransferResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MsgTransferResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ibc.applications.transfer.v1.Tx.MsgTransferResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ibc_applications_transfer_v1_MsgTransfer_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ibc_applications_transfer_v1_MsgTransfer_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ibc_applications_transfer_v1_MsgTransferResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ibc_applications_transfer_v1_MsgTransferResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n%ibc/applications/transfer/v1/tx.proto\022" +
      "\034ibc.applications.transfer.v1\032\024gogoproto" +
      "/gogo.proto\032\036cosmos/base/v1beta1/coin.pr" +
      "oto\032\037ibc/core/client/v1/client.proto\"\325\002\n" +
      "\013MsgTransfer\022+\n\013source_port\030\001 \001(\tB\026\362\336\037\022y" +
      "aml:\"source_port\"\0221\n\016source_channel\030\002 \001(" +
      "\tB\031\362\336\037\025yaml:\"source_channel\"\022.\n\005token\030\003 " +
      "\001(\0132\031.cosmos.base.v1beta1.CoinB\004\310\336\037\000\022\016\n\006" +
      "sender\030\004 \001(\t\022\020\n\010receiver\030\005 \001(\t\022Q\n\016timeou" +
      "t_height\030\006 \001(\0132\032.ibc.core.client.v1.Heig" +
      "htB\035\362\336\037\025yaml:\"timeout_height\"\310\336\037\000\0227\n\021tim" +
      "eout_timestamp\030\007 \001(\004B\034\362\336\037\030yaml:\"timeout_" +
      "timestamp\":\010\350\240\037\000\210\240\037\000\"\025\n\023MsgTransferRespo" +
      "nse2o\n\003Msg\022h\n\010Transfer\022).ibc.application" +
      "s.transfer.v1.MsgTransfer\0321.ibc.applicat" +
      "ions.transfer.v1.MsgTransferResponseB6Z4" +
      "github.com/cosmos/ibc-go/modules/apps/tr" +
      "ansfer/typesb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.GoGoProtos.getDescriptor(),
          cosmos.base.v1beta1.CoinOuterClass.getDescriptor(),
          ibc.core.client.v1.Client.getDescriptor(),
        });
    internal_static_ibc_applications_transfer_v1_MsgTransfer_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ibc_applications_transfer_v1_MsgTransfer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ibc_applications_transfer_v1_MsgTransfer_descriptor,
        new java.lang.String[] { "SourcePort", "SourceChannel", "Token", "Sender", "Receiver", "TimeoutHeight", "TimeoutTimestamp", });
    internal_static_ibc_applications_transfer_v1_MsgTransferResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ibc_applications_transfer_v1_MsgTransferResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ibc_applications_transfer_v1_MsgTransferResponse_descriptor,
        new java.lang.String[] { });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.protobuf.GoGoProtos.equal);
    registry.add(com.google.protobuf.GoGoProtos.goprotoGetters);
    registry.add(com.google.protobuf.GoGoProtos.moretags);
    registry.add(com.google.protobuf.GoGoProtos.nullable);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.protobuf.GoGoProtos.getDescriptor();
    cosmos.base.v1beta1.CoinOuterClass.getDescriptor();
    ibc.core.client.v1.Client.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
