// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: terra/wasm/v1beta1/wasm.proto

package terra.wasm.v1beta1;

public final class Wasm {
  private Wasm() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ParamsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:terra.wasm.v1beta1.Params)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint64 max_contract_size = 1 [(.gogoproto.moretags) = "yaml:&#92;"max_contract_size&#92;""];</code>
     * @return The maxContractSize.
     */
    long getMaxContractSize();

    /**
     * <code>uint64 max_contract_gas = 2 [(.gogoproto.moretags) = "yaml:&#92;"max_contract_gas&#92;""];</code>
     * @return The maxContractGas.
     */
    long getMaxContractGas();

    /**
     * <code>uint64 max_contract_msg_size = 3 [(.gogoproto.moretags) = "yaml:&#92;"max_contract_msg_size&#92;""];</code>
     * @return The maxContractMsgSize.
     */
    long getMaxContractMsgSize();
  }
  /**
   * <pre>
   * Params defines the parameters for the wasm module.
   * </pre>
   *
   * Protobuf type {@code terra.wasm.v1beta1.Params}
   */
  public static final class Params extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:terra.wasm.v1beta1.Params)
      ParamsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Params.newBuilder() to construct.
    private Params(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Params() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Params();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return terra.wasm.v1beta1.Wasm.internal_static_terra_wasm_v1beta1_Params_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return terra.wasm.v1beta1.Wasm.internal_static_terra_wasm_v1beta1_Params_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              terra.wasm.v1beta1.Wasm.Params.class, terra.wasm.v1beta1.Wasm.Params.Builder.class);
    }

    public static final int MAX_CONTRACT_SIZE_FIELD_NUMBER = 1;
    private long maxContractSize_ = 0L;
    /**
     * <code>uint64 max_contract_size = 1 [(.gogoproto.moretags) = "yaml:&#92;"max_contract_size&#92;""];</code>
     * @return The maxContractSize.
     */
    @java.lang.Override
    public long getMaxContractSize() {
      return maxContractSize_;
    }

    public static final int MAX_CONTRACT_GAS_FIELD_NUMBER = 2;
    private long maxContractGas_ = 0L;
    /**
     * <code>uint64 max_contract_gas = 2 [(.gogoproto.moretags) = "yaml:&#92;"max_contract_gas&#92;""];</code>
     * @return The maxContractGas.
     */
    @java.lang.Override
    public long getMaxContractGas() {
      return maxContractGas_;
    }

    public static final int MAX_CONTRACT_MSG_SIZE_FIELD_NUMBER = 3;
    private long maxContractMsgSize_ = 0L;
    /**
     * <code>uint64 max_contract_msg_size = 3 [(.gogoproto.moretags) = "yaml:&#92;"max_contract_msg_size&#92;""];</code>
     * @return The maxContractMsgSize.
     */
    @java.lang.Override
    public long getMaxContractMsgSize() {
      return maxContractMsgSize_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (maxContractSize_ != 0L) {
        output.writeUInt64(1, maxContractSize_);
      }
      if (maxContractGas_ != 0L) {
        output.writeUInt64(2, maxContractGas_);
      }
      if (maxContractMsgSize_ != 0L) {
        output.writeUInt64(3, maxContractMsgSize_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (maxContractSize_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, maxContractSize_);
      }
      if (maxContractGas_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, maxContractGas_);
      }
      if (maxContractMsgSize_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, maxContractMsgSize_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof terra.wasm.v1beta1.Wasm.Params)) {
        return super.equals(obj);
      }
      terra.wasm.v1beta1.Wasm.Params other = (terra.wasm.v1beta1.Wasm.Params) obj;

      if (getMaxContractSize()
          != other.getMaxContractSize()) return false;
      if (getMaxContractGas()
          != other.getMaxContractGas()) return false;
      if (getMaxContractMsgSize()
          != other.getMaxContractMsgSize()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MAX_CONTRACT_SIZE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMaxContractSize());
      hash = (37 * hash) + MAX_CONTRACT_GAS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMaxContractGas());
      hash = (37 * hash) + MAX_CONTRACT_MSG_SIZE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMaxContractMsgSize());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static terra.wasm.v1beta1.Wasm.Params parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static terra.wasm.v1beta1.Wasm.Params parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static terra.wasm.v1beta1.Wasm.Params parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static terra.wasm.v1beta1.Wasm.Params parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static terra.wasm.v1beta1.Wasm.Params parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static terra.wasm.v1beta1.Wasm.Params parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static terra.wasm.v1beta1.Wasm.Params parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static terra.wasm.v1beta1.Wasm.Params parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static terra.wasm.v1beta1.Wasm.Params parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static terra.wasm.v1beta1.Wasm.Params parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static terra.wasm.v1beta1.Wasm.Params parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static terra.wasm.v1beta1.Wasm.Params parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(terra.wasm.v1beta1.Wasm.Params prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Params defines the parameters for the wasm module.
     * </pre>
     *
     * Protobuf type {@code terra.wasm.v1beta1.Params}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:terra.wasm.v1beta1.Params)
        terra.wasm.v1beta1.Wasm.ParamsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return terra.wasm.v1beta1.Wasm.internal_static_terra_wasm_v1beta1_Params_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return terra.wasm.v1beta1.Wasm.internal_static_terra_wasm_v1beta1_Params_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                terra.wasm.v1beta1.Wasm.Params.class, terra.wasm.v1beta1.Wasm.Params.Builder.class);
      }

      // Construct using terra.wasm.v1beta1.Wasm.Params.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        maxContractSize_ = 0L;
        maxContractGas_ = 0L;
        maxContractMsgSize_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return terra.wasm.v1beta1.Wasm.internal_static_terra_wasm_v1beta1_Params_descriptor;
      }

      @java.lang.Override
      public terra.wasm.v1beta1.Wasm.Params getDefaultInstanceForType() {
        return terra.wasm.v1beta1.Wasm.Params.getDefaultInstance();
      }

      @java.lang.Override
      public terra.wasm.v1beta1.Wasm.Params build() {
        terra.wasm.v1beta1.Wasm.Params result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public terra.wasm.v1beta1.Wasm.Params buildPartial() {
        terra.wasm.v1beta1.Wasm.Params result = new terra.wasm.v1beta1.Wasm.Params(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(terra.wasm.v1beta1.Wasm.Params result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.maxContractSize_ = maxContractSize_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.maxContractGas_ = maxContractGas_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.maxContractMsgSize_ = maxContractMsgSize_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof terra.wasm.v1beta1.Wasm.Params) {
          return mergeFrom((terra.wasm.v1beta1.Wasm.Params)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(terra.wasm.v1beta1.Wasm.Params other) {
        if (other == terra.wasm.v1beta1.Wasm.Params.getDefaultInstance()) return this;
        if (other.getMaxContractSize() != 0L) {
          setMaxContractSize(other.getMaxContractSize());
        }
        if (other.getMaxContractGas() != 0L) {
          setMaxContractGas(other.getMaxContractGas());
        }
        if (other.getMaxContractMsgSize() != 0L) {
          setMaxContractMsgSize(other.getMaxContractMsgSize());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                maxContractSize_ = input.readUInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                maxContractGas_ = input.readUInt64();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                maxContractMsgSize_ = input.readUInt64();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long maxContractSize_ ;
      /**
       * <code>uint64 max_contract_size = 1 [(.gogoproto.moretags) = "yaml:&#92;"max_contract_size&#92;""];</code>
       * @return The maxContractSize.
       */
      @java.lang.Override
      public long getMaxContractSize() {
        return maxContractSize_;
      }
      /**
       * <code>uint64 max_contract_size = 1 [(.gogoproto.moretags) = "yaml:&#92;"max_contract_size&#92;""];</code>
       * @param value The maxContractSize to set.
       * @return This builder for chaining.
       */
      public Builder setMaxContractSize(long value) {
        
        maxContractSize_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 max_contract_size = 1 [(.gogoproto.moretags) = "yaml:&#92;"max_contract_size&#92;""];</code>
       * @return This builder for chaining.
       */
      public Builder clearMaxContractSize() {
        bitField0_ = (bitField0_ & ~0x00000001);
        maxContractSize_ = 0L;
        onChanged();
        return this;
      }

      private long maxContractGas_ ;
      /**
       * <code>uint64 max_contract_gas = 2 [(.gogoproto.moretags) = "yaml:&#92;"max_contract_gas&#92;""];</code>
       * @return The maxContractGas.
       */
      @java.lang.Override
      public long getMaxContractGas() {
        return maxContractGas_;
      }
      /**
       * <code>uint64 max_contract_gas = 2 [(.gogoproto.moretags) = "yaml:&#92;"max_contract_gas&#92;""];</code>
       * @param value The maxContractGas to set.
       * @return This builder for chaining.
       */
      public Builder setMaxContractGas(long value) {
        
        maxContractGas_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 max_contract_gas = 2 [(.gogoproto.moretags) = "yaml:&#92;"max_contract_gas&#92;""];</code>
       * @return This builder for chaining.
       */
      public Builder clearMaxContractGas() {
        bitField0_ = (bitField0_ & ~0x00000002);
        maxContractGas_ = 0L;
        onChanged();
        return this;
      }

      private long maxContractMsgSize_ ;
      /**
       * <code>uint64 max_contract_msg_size = 3 [(.gogoproto.moretags) = "yaml:&#92;"max_contract_msg_size&#92;""];</code>
       * @return The maxContractMsgSize.
       */
      @java.lang.Override
      public long getMaxContractMsgSize() {
        return maxContractMsgSize_;
      }
      /**
       * <code>uint64 max_contract_msg_size = 3 [(.gogoproto.moretags) = "yaml:&#92;"max_contract_msg_size&#92;""];</code>
       * @param value The maxContractMsgSize to set.
       * @return This builder for chaining.
       */
      public Builder setMaxContractMsgSize(long value) {
        
        maxContractMsgSize_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 max_contract_msg_size = 3 [(.gogoproto.moretags) = "yaml:&#92;"max_contract_msg_size&#92;""];</code>
       * @return This builder for chaining.
       */
      public Builder clearMaxContractMsgSize() {
        bitField0_ = (bitField0_ & ~0x00000004);
        maxContractMsgSize_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:terra.wasm.v1beta1.Params)
    }

    // @@protoc_insertion_point(class_scope:terra.wasm.v1beta1.Params)
    private static final terra.wasm.v1beta1.Wasm.Params DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new terra.wasm.v1beta1.Wasm.Params();
    }

    public static terra.wasm.v1beta1.Wasm.Params getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Params>
        PARSER = new com.google.protobuf.AbstractParser<Params>() {
      @java.lang.Override
      public Params parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Params> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Params> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public terra.wasm.v1beta1.Wasm.Params getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CodeInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:terra.wasm.v1beta1.CodeInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * CodeID is the sequentially increasing unique identifier
     * </pre>
     *
     * <code>uint64 code_id = 1 [(.gogoproto.customname) = "CodeID", (.gogoproto.moretags) = "yaml:&#92;"code_id&#92;""];</code>
     * @return The codeId.
     */
    long getCodeId();

    /**
     * <pre>
     * CodeHash is the unique identifier created by wasmvm
     * </pre>
     *
     * <code>bytes code_hash = 2 [(.gogoproto.moretags) = "yaml:&#92;"code_hash&#92;""];</code>
     * @return The codeHash.
     */
    com.google.protobuf.ByteString getCodeHash();

    /**
     * <pre>
     * Creator address who initially stored the code
     * </pre>
     *
     * <code>string creator = 3 [(.gogoproto.moretags) = "yaml:&#92;"creator&#92;""];</code>
     * @return The creator.
     */
    java.lang.String getCreator();
    /**
     * <pre>
     * Creator address who initially stored the code
     * </pre>
     *
     * <code>string creator = 3 [(.gogoproto.moretags) = "yaml:&#92;"creator&#92;""];</code>
     * @return The bytes for creator.
     */
    com.google.protobuf.ByteString
        getCreatorBytes();
  }
  /**
   * <pre>
   * CodeInfo is data for the uploaded contract WASM code
   * </pre>
   *
   * Protobuf type {@code terra.wasm.v1beta1.CodeInfo}
   */
  public static final class CodeInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:terra.wasm.v1beta1.CodeInfo)
      CodeInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CodeInfo.newBuilder() to construct.
    private CodeInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CodeInfo() {
      codeHash_ = com.google.protobuf.ByteString.EMPTY;
      creator_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CodeInfo();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return terra.wasm.v1beta1.Wasm.internal_static_terra_wasm_v1beta1_CodeInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return terra.wasm.v1beta1.Wasm.internal_static_terra_wasm_v1beta1_CodeInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              terra.wasm.v1beta1.Wasm.CodeInfo.class, terra.wasm.v1beta1.Wasm.CodeInfo.Builder.class);
    }

    public static final int CODE_ID_FIELD_NUMBER = 1;
    private long codeId_ = 0L;
    /**
     * <pre>
     * CodeID is the sequentially increasing unique identifier
     * </pre>
     *
     * <code>uint64 code_id = 1 [(.gogoproto.customname) = "CodeID", (.gogoproto.moretags) = "yaml:&#92;"code_id&#92;""];</code>
     * @return The codeId.
     */
    @java.lang.Override
    public long getCodeId() {
      return codeId_;
    }

    public static final int CODE_HASH_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString codeHash_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * CodeHash is the unique identifier created by wasmvm
     * </pre>
     *
     * <code>bytes code_hash = 2 [(.gogoproto.moretags) = "yaml:&#92;"code_hash&#92;""];</code>
     * @return The codeHash.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getCodeHash() {
      return codeHash_;
    }

    public static final int CREATOR_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object creator_ = "";
    /**
     * <pre>
     * Creator address who initially stored the code
     * </pre>
     *
     * <code>string creator = 3 [(.gogoproto.moretags) = "yaml:&#92;"creator&#92;""];</code>
     * @return The creator.
     */
    @java.lang.Override
    public java.lang.String getCreator() {
      java.lang.Object ref = creator_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        creator_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Creator address who initially stored the code
     * </pre>
     *
     * <code>string creator = 3 [(.gogoproto.moretags) = "yaml:&#92;"creator&#92;""];</code>
     * @return The bytes for creator.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCreatorBytes() {
      java.lang.Object ref = creator_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        creator_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (codeId_ != 0L) {
        output.writeUInt64(1, codeId_);
      }
      if (!codeHash_.isEmpty()) {
        output.writeBytes(2, codeHash_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(creator_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, creator_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (codeId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, codeId_);
      }
      if (!codeHash_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, codeHash_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(creator_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, creator_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof terra.wasm.v1beta1.Wasm.CodeInfo)) {
        return super.equals(obj);
      }
      terra.wasm.v1beta1.Wasm.CodeInfo other = (terra.wasm.v1beta1.Wasm.CodeInfo) obj;

      if (getCodeId()
          != other.getCodeId()) return false;
      if (!getCodeHash()
          .equals(other.getCodeHash())) return false;
      if (!getCreator()
          .equals(other.getCreator())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CODE_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCodeId());
      hash = (37 * hash) + CODE_HASH_FIELD_NUMBER;
      hash = (53 * hash) + getCodeHash().hashCode();
      hash = (37 * hash) + CREATOR_FIELD_NUMBER;
      hash = (53 * hash) + getCreator().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static terra.wasm.v1beta1.Wasm.CodeInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static terra.wasm.v1beta1.Wasm.CodeInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static terra.wasm.v1beta1.Wasm.CodeInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static terra.wasm.v1beta1.Wasm.CodeInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static terra.wasm.v1beta1.Wasm.CodeInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static terra.wasm.v1beta1.Wasm.CodeInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static terra.wasm.v1beta1.Wasm.CodeInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static terra.wasm.v1beta1.Wasm.CodeInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static terra.wasm.v1beta1.Wasm.CodeInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static terra.wasm.v1beta1.Wasm.CodeInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static terra.wasm.v1beta1.Wasm.CodeInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static terra.wasm.v1beta1.Wasm.CodeInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(terra.wasm.v1beta1.Wasm.CodeInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * CodeInfo is data for the uploaded contract WASM code
     * </pre>
     *
     * Protobuf type {@code terra.wasm.v1beta1.CodeInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:terra.wasm.v1beta1.CodeInfo)
        terra.wasm.v1beta1.Wasm.CodeInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return terra.wasm.v1beta1.Wasm.internal_static_terra_wasm_v1beta1_CodeInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return terra.wasm.v1beta1.Wasm.internal_static_terra_wasm_v1beta1_CodeInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                terra.wasm.v1beta1.Wasm.CodeInfo.class, terra.wasm.v1beta1.Wasm.CodeInfo.Builder.class);
      }

      // Construct using terra.wasm.v1beta1.Wasm.CodeInfo.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        codeId_ = 0L;
        codeHash_ = com.google.protobuf.ByteString.EMPTY;
        creator_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return terra.wasm.v1beta1.Wasm.internal_static_terra_wasm_v1beta1_CodeInfo_descriptor;
      }

      @java.lang.Override
      public terra.wasm.v1beta1.Wasm.CodeInfo getDefaultInstanceForType() {
        return terra.wasm.v1beta1.Wasm.CodeInfo.getDefaultInstance();
      }

      @java.lang.Override
      public terra.wasm.v1beta1.Wasm.CodeInfo build() {
        terra.wasm.v1beta1.Wasm.CodeInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public terra.wasm.v1beta1.Wasm.CodeInfo buildPartial() {
        terra.wasm.v1beta1.Wasm.CodeInfo result = new terra.wasm.v1beta1.Wasm.CodeInfo(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(terra.wasm.v1beta1.Wasm.CodeInfo result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.codeId_ = codeId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.codeHash_ = codeHash_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.creator_ = creator_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof terra.wasm.v1beta1.Wasm.CodeInfo) {
          return mergeFrom((terra.wasm.v1beta1.Wasm.CodeInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(terra.wasm.v1beta1.Wasm.CodeInfo other) {
        if (other == terra.wasm.v1beta1.Wasm.CodeInfo.getDefaultInstance()) return this;
        if (other.getCodeId() != 0L) {
          setCodeId(other.getCodeId());
        }
        if (other.getCodeHash() != com.google.protobuf.ByteString.EMPTY) {
          setCodeHash(other.getCodeHash());
        }
        if (!other.getCreator().isEmpty()) {
          creator_ = other.creator_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                codeId_ = input.readUInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                codeHash_ = input.readBytes();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                creator_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long codeId_ ;
      /**
       * <pre>
       * CodeID is the sequentially increasing unique identifier
       * </pre>
       *
       * <code>uint64 code_id = 1 [(.gogoproto.customname) = "CodeID", (.gogoproto.moretags) = "yaml:&#92;"code_id&#92;""];</code>
       * @return The codeId.
       */
      @java.lang.Override
      public long getCodeId() {
        return codeId_;
      }
      /**
       * <pre>
       * CodeID is the sequentially increasing unique identifier
       * </pre>
       *
       * <code>uint64 code_id = 1 [(.gogoproto.customname) = "CodeID", (.gogoproto.moretags) = "yaml:&#92;"code_id&#92;""];</code>
       * @param value The codeId to set.
       * @return This builder for chaining.
       */
      public Builder setCodeId(long value) {
        
        codeId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * CodeID is the sequentially increasing unique identifier
       * </pre>
       *
       * <code>uint64 code_id = 1 [(.gogoproto.customname) = "CodeID", (.gogoproto.moretags) = "yaml:&#92;"code_id&#92;""];</code>
       * @return This builder for chaining.
       */
      public Builder clearCodeId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        codeId_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString codeHash_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * CodeHash is the unique identifier created by wasmvm
       * </pre>
       *
       * <code>bytes code_hash = 2 [(.gogoproto.moretags) = "yaml:&#92;"code_hash&#92;""];</code>
       * @return The codeHash.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getCodeHash() {
        return codeHash_;
      }
      /**
       * <pre>
       * CodeHash is the unique identifier created by wasmvm
       * </pre>
       *
       * <code>bytes code_hash = 2 [(.gogoproto.moretags) = "yaml:&#92;"code_hash&#92;""];</code>
       * @param value The codeHash to set.
       * @return This builder for chaining.
       */
      public Builder setCodeHash(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        codeHash_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * CodeHash is the unique identifier created by wasmvm
       * </pre>
       *
       * <code>bytes code_hash = 2 [(.gogoproto.moretags) = "yaml:&#92;"code_hash&#92;""];</code>
       * @return This builder for chaining.
       */
      public Builder clearCodeHash() {
        bitField0_ = (bitField0_ & ~0x00000002);
        codeHash_ = getDefaultInstance().getCodeHash();
        onChanged();
        return this;
      }

      private java.lang.Object creator_ = "";
      /**
       * <pre>
       * Creator address who initially stored the code
       * </pre>
       *
       * <code>string creator = 3 [(.gogoproto.moretags) = "yaml:&#92;"creator&#92;""];</code>
       * @return The creator.
       */
      public java.lang.String getCreator() {
        java.lang.Object ref = creator_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          creator_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Creator address who initially stored the code
       * </pre>
       *
       * <code>string creator = 3 [(.gogoproto.moretags) = "yaml:&#92;"creator&#92;""];</code>
       * @return The bytes for creator.
       */
      public com.google.protobuf.ByteString
          getCreatorBytes() {
        java.lang.Object ref = creator_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          creator_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Creator address who initially stored the code
       * </pre>
       *
       * <code>string creator = 3 [(.gogoproto.moretags) = "yaml:&#92;"creator&#92;""];</code>
       * @param value The creator to set.
       * @return This builder for chaining.
       */
      public Builder setCreator(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        creator_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Creator address who initially stored the code
       * </pre>
       *
       * <code>string creator = 3 [(.gogoproto.moretags) = "yaml:&#92;"creator&#92;""];</code>
       * @return This builder for chaining.
       */
      public Builder clearCreator() {
        creator_ = getDefaultInstance().getCreator();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Creator address who initially stored the code
       * </pre>
       *
       * <code>string creator = 3 [(.gogoproto.moretags) = "yaml:&#92;"creator&#92;""];</code>
       * @param value The bytes for creator to set.
       * @return This builder for chaining.
       */
      public Builder setCreatorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        creator_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:terra.wasm.v1beta1.CodeInfo)
    }

    // @@protoc_insertion_point(class_scope:terra.wasm.v1beta1.CodeInfo)
    private static final terra.wasm.v1beta1.Wasm.CodeInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new terra.wasm.v1beta1.Wasm.CodeInfo();
    }

    public static terra.wasm.v1beta1.Wasm.CodeInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CodeInfo>
        PARSER = new com.google.protobuf.AbstractParser<CodeInfo>() {
      @java.lang.Override
      public CodeInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<CodeInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CodeInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public terra.wasm.v1beta1.Wasm.CodeInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ContractInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:terra.wasm.v1beta1.ContractInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Address is the address of the contract
     * </pre>
     *
     * <code>string address = 1 [(.gogoproto.moretags) = "yaml:&#92;"address&#92;""];</code>
     * @return The address.
     */
    java.lang.String getAddress();
    /**
     * <pre>
     * Address is the address of the contract
     * </pre>
     *
     * <code>string address = 1 [(.gogoproto.moretags) = "yaml:&#92;"address&#92;""];</code>
     * @return The bytes for address.
     */
    com.google.protobuf.ByteString
        getAddressBytes();

    /**
     * <pre>
     * Creator is the contract creator address
     * </pre>
     *
     * <code>string creator = 2 [(.gogoproto.moretags) = "yaml:&#92;"creator&#92;""];</code>
     * @return The creator.
     */
    java.lang.String getCreator();
    /**
     * <pre>
     * Creator is the contract creator address
     * </pre>
     *
     * <code>string creator = 2 [(.gogoproto.moretags) = "yaml:&#92;"creator&#92;""];</code>
     * @return The bytes for creator.
     */
    com.google.protobuf.ByteString
        getCreatorBytes();

    /**
     * <pre>
     * Admin is who can execute the contract migration
     * </pre>
     *
     * <code>string admin = 3 [(.gogoproto.moretags) = "yaml:&#92;"admin&#92;""];</code>
     * @return The admin.
     */
    java.lang.String getAdmin();
    /**
     * <pre>
     * Admin is who can execute the contract migration
     * </pre>
     *
     * <code>string admin = 3 [(.gogoproto.moretags) = "yaml:&#92;"admin&#92;""];</code>
     * @return The bytes for admin.
     */
    com.google.protobuf.ByteString
        getAdminBytes();

    /**
     * <pre>
     * CodeID is the reference to the stored Wasm code
     * </pre>
     *
     * <code>uint64 code_id = 4 [(.gogoproto.customname) = "CodeID", (.gogoproto.moretags) = "yaml:&#92;"code_id&#92;""];</code>
     * @return The codeId.
     */
    long getCodeId();

    /**
     * <pre>
     * InitMsg is the raw message used when instantiating a contract
     * </pre>
     *
     * <code>bytes init_msg = 5 [(.gogoproto.moretags) = "yaml:&#92;"init_msg&#92;"", (.gogoproto.casttype) = "encoding/json.RawMessage"];</code>
     * @return The initMsg.
     */
    com.google.protobuf.ByteString getInitMsg();
  }
  /**
   * <pre>
   * ContractInfo stores a WASM contract instance
   * </pre>
   *
   * Protobuf type {@code terra.wasm.v1beta1.ContractInfo}
   */
  public static final class ContractInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:terra.wasm.v1beta1.ContractInfo)
      ContractInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ContractInfo.newBuilder() to construct.
    private ContractInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ContractInfo() {
      address_ = "";
      creator_ = "";
      admin_ = "";
      initMsg_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ContractInfo();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return terra.wasm.v1beta1.Wasm.internal_static_terra_wasm_v1beta1_ContractInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return terra.wasm.v1beta1.Wasm.internal_static_terra_wasm_v1beta1_ContractInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              terra.wasm.v1beta1.Wasm.ContractInfo.class, terra.wasm.v1beta1.Wasm.ContractInfo.Builder.class);
    }

    public static final int ADDRESS_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object address_ = "";
    /**
     * <pre>
     * Address is the address of the contract
     * </pre>
     *
     * <code>string address = 1 [(.gogoproto.moretags) = "yaml:&#92;"address&#92;""];</code>
     * @return The address.
     */
    @java.lang.Override
    public java.lang.String getAddress() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        address_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Address is the address of the contract
     * </pre>
     *
     * <code>string address = 1 [(.gogoproto.moretags) = "yaml:&#92;"address&#92;""];</code>
     * @return The bytes for address.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAddressBytes() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CREATOR_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object creator_ = "";
    /**
     * <pre>
     * Creator is the contract creator address
     * </pre>
     *
     * <code>string creator = 2 [(.gogoproto.moretags) = "yaml:&#92;"creator&#92;""];</code>
     * @return The creator.
     */
    @java.lang.Override
    public java.lang.String getCreator() {
      java.lang.Object ref = creator_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        creator_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Creator is the contract creator address
     * </pre>
     *
     * <code>string creator = 2 [(.gogoproto.moretags) = "yaml:&#92;"creator&#92;""];</code>
     * @return The bytes for creator.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCreatorBytes() {
      java.lang.Object ref = creator_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        creator_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ADMIN_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object admin_ = "";
    /**
     * <pre>
     * Admin is who can execute the contract migration
     * </pre>
     *
     * <code>string admin = 3 [(.gogoproto.moretags) = "yaml:&#92;"admin&#92;""];</code>
     * @return The admin.
     */
    @java.lang.Override
    public java.lang.String getAdmin() {
      java.lang.Object ref = admin_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        admin_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Admin is who can execute the contract migration
     * </pre>
     *
     * <code>string admin = 3 [(.gogoproto.moretags) = "yaml:&#92;"admin&#92;""];</code>
     * @return The bytes for admin.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAdminBytes() {
      java.lang.Object ref = admin_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        admin_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CODE_ID_FIELD_NUMBER = 4;
    private long codeId_ = 0L;
    /**
     * <pre>
     * CodeID is the reference to the stored Wasm code
     * </pre>
     *
     * <code>uint64 code_id = 4 [(.gogoproto.customname) = "CodeID", (.gogoproto.moretags) = "yaml:&#92;"code_id&#92;""];</code>
     * @return The codeId.
     */
    @java.lang.Override
    public long getCodeId() {
      return codeId_;
    }

    public static final int INIT_MSG_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString initMsg_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * InitMsg is the raw message used when instantiating a contract
     * </pre>
     *
     * <code>bytes init_msg = 5 [(.gogoproto.moretags) = "yaml:&#92;"init_msg&#92;"", (.gogoproto.casttype) = "encoding/json.RawMessage"];</code>
     * @return The initMsg.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getInitMsg() {
      return initMsg_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(address_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, address_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(creator_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, creator_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(admin_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, admin_);
      }
      if (codeId_ != 0L) {
        output.writeUInt64(4, codeId_);
      }
      if (!initMsg_.isEmpty()) {
        output.writeBytes(5, initMsg_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(address_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, address_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(creator_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, creator_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(admin_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, admin_);
      }
      if (codeId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(4, codeId_);
      }
      if (!initMsg_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, initMsg_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof terra.wasm.v1beta1.Wasm.ContractInfo)) {
        return super.equals(obj);
      }
      terra.wasm.v1beta1.Wasm.ContractInfo other = (terra.wasm.v1beta1.Wasm.ContractInfo) obj;

      if (!getAddress()
          .equals(other.getAddress())) return false;
      if (!getCreator()
          .equals(other.getCreator())) return false;
      if (!getAdmin()
          .equals(other.getAdmin())) return false;
      if (getCodeId()
          != other.getCodeId()) return false;
      if (!getInitMsg()
          .equals(other.getInitMsg())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getAddress().hashCode();
      hash = (37 * hash) + CREATOR_FIELD_NUMBER;
      hash = (53 * hash) + getCreator().hashCode();
      hash = (37 * hash) + ADMIN_FIELD_NUMBER;
      hash = (53 * hash) + getAdmin().hashCode();
      hash = (37 * hash) + CODE_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCodeId());
      hash = (37 * hash) + INIT_MSG_FIELD_NUMBER;
      hash = (53 * hash) + getInitMsg().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static terra.wasm.v1beta1.Wasm.ContractInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static terra.wasm.v1beta1.Wasm.ContractInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static terra.wasm.v1beta1.Wasm.ContractInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static terra.wasm.v1beta1.Wasm.ContractInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static terra.wasm.v1beta1.Wasm.ContractInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static terra.wasm.v1beta1.Wasm.ContractInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static terra.wasm.v1beta1.Wasm.ContractInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static terra.wasm.v1beta1.Wasm.ContractInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static terra.wasm.v1beta1.Wasm.ContractInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static terra.wasm.v1beta1.Wasm.ContractInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static terra.wasm.v1beta1.Wasm.ContractInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static terra.wasm.v1beta1.Wasm.ContractInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(terra.wasm.v1beta1.Wasm.ContractInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * ContractInfo stores a WASM contract instance
     * </pre>
     *
     * Protobuf type {@code terra.wasm.v1beta1.ContractInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:terra.wasm.v1beta1.ContractInfo)
        terra.wasm.v1beta1.Wasm.ContractInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return terra.wasm.v1beta1.Wasm.internal_static_terra_wasm_v1beta1_ContractInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return terra.wasm.v1beta1.Wasm.internal_static_terra_wasm_v1beta1_ContractInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                terra.wasm.v1beta1.Wasm.ContractInfo.class, terra.wasm.v1beta1.Wasm.ContractInfo.Builder.class);
      }

      // Construct using terra.wasm.v1beta1.Wasm.ContractInfo.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        address_ = "";
        creator_ = "";
        admin_ = "";
        codeId_ = 0L;
        initMsg_ = com.google.protobuf.ByteString.EMPTY;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return terra.wasm.v1beta1.Wasm.internal_static_terra_wasm_v1beta1_ContractInfo_descriptor;
      }

      @java.lang.Override
      public terra.wasm.v1beta1.Wasm.ContractInfo getDefaultInstanceForType() {
        return terra.wasm.v1beta1.Wasm.ContractInfo.getDefaultInstance();
      }

      @java.lang.Override
      public terra.wasm.v1beta1.Wasm.ContractInfo build() {
        terra.wasm.v1beta1.Wasm.ContractInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public terra.wasm.v1beta1.Wasm.ContractInfo buildPartial() {
        terra.wasm.v1beta1.Wasm.ContractInfo result = new terra.wasm.v1beta1.Wasm.ContractInfo(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(terra.wasm.v1beta1.Wasm.ContractInfo result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.address_ = address_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.creator_ = creator_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.admin_ = admin_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.codeId_ = codeId_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.initMsg_ = initMsg_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof terra.wasm.v1beta1.Wasm.ContractInfo) {
          return mergeFrom((terra.wasm.v1beta1.Wasm.ContractInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(terra.wasm.v1beta1.Wasm.ContractInfo other) {
        if (other == terra.wasm.v1beta1.Wasm.ContractInfo.getDefaultInstance()) return this;
        if (!other.getAddress().isEmpty()) {
          address_ = other.address_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getCreator().isEmpty()) {
          creator_ = other.creator_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getAdmin().isEmpty()) {
          admin_ = other.admin_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (other.getCodeId() != 0L) {
          setCodeId(other.getCodeId());
        }
        if (other.getInitMsg() != com.google.protobuf.ByteString.EMPTY) {
          setInitMsg(other.getInitMsg());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                address_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                creator_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                admin_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 32: {
                codeId_ = input.readUInt64();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 42: {
                initMsg_ = input.readBytes();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object address_ = "";
      /**
       * <pre>
       * Address is the address of the contract
       * </pre>
       *
       * <code>string address = 1 [(.gogoproto.moretags) = "yaml:&#92;"address&#92;""];</code>
       * @return The address.
       */
      public java.lang.String getAddress() {
        java.lang.Object ref = address_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          address_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Address is the address of the contract
       * </pre>
       *
       * <code>string address = 1 [(.gogoproto.moretags) = "yaml:&#92;"address&#92;""];</code>
       * @return The bytes for address.
       */
      public com.google.protobuf.ByteString
          getAddressBytes() {
        java.lang.Object ref = address_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          address_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Address is the address of the contract
       * </pre>
       *
       * <code>string address = 1 [(.gogoproto.moretags) = "yaml:&#92;"address&#92;""];</code>
       * @param value The address to set.
       * @return This builder for chaining.
       */
      public Builder setAddress(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        address_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Address is the address of the contract
       * </pre>
       *
       * <code>string address = 1 [(.gogoproto.moretags) = "yaml:&#92;"address&#92;""];</code>
       * @return This builder for chaining.
       */
      public Builder clearAddress() {
        address_ = getDefaultInstance().getAddress();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Address is the address of the contract
       * </pre>
       *
       * <code>string address = 1 [(.gogoproto.moretags) = "yaml:&#92;"address&#92;""];</code>
       * @param value The bytes for address to set.
       * @return This builder for chaining.
       */
      public Builder setAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        address_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object creator_ = "";
      /**
       * <pre>
       * Creator is the contract creator address
       * </pre>
       *
       * <code>string creator = 2 [(.gogoproto.moretags) = "yaml:&#92;"creator&#92;""];</code>
       * @return The creator.
       */
      public java.lang.String getCreator() {
        java.lang.Object ref = creator_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          creator_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Creator is the contract creator address
       * </pre>
       *
       * <code>string creator = 2 [(.gogoproto.moretags) = "yaml:&#92;"creator&#92;""];</code>
       * @return The bytes for creator.
       */
      public com.google.protobuf.ByteString
          getCreatorBytes() {
        java.lang.Object ref = creator_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          creator_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Creator is the contract creator address
       * </pre>
       *
       * <code>string creator = 2 [(.gogoproto.moretags) = "yaml:&#92;"creator&#92;""];</code>
       * @param value The creator to set.
       * @return This builder for chaining.
       */
      public Builder setCreator(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        creator_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Creator is the contract creator address
       * </pre>
       *
       * <code>string creator = 2 [(.gogoproto.moretags) = "yaml:&#92;"creator&#92;""];</code>
       * @return This builder for chaining.
       */
      public Builder clearCreator() {
        creator_ = getDefaultInstance().getCreator();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Creator is the contract creator address
       * </pre>
       *
       * <code>string creator = 2 [(.gogoproto.moretags) = "yaml:&#92;"creator&#92;""];</code>
       * @param value The bytes for creator to set.
       * @return This builder for chaining.
       */
      public Builder setCreatorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        creator_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object admin_ = "";
      /**
       * <pre>
       * Admin is who can execute the contract migration
       * </pre>
       *
       * <code>string admin = 3 [(.gogoproto.moretags) = "yaml:&#92;"admin&#92;""];</code>
       * @return The admin.
       */
      public java.lang.String getAdmin() {
        java.lang.Object ref = admin_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          admin_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Admin is who can execute the contract migration
       * </pre>
       *
       * <code>string admin = 3 [(.gogoproto.moretags) = "yaml:&#92;"admin&#92;""];</code>
       * @return The bytes for admin.
       */
      public com.google.protobuf.ByteString
          getAdminBytes() {
        java.lang.Object ref = admin_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          admin_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Admin is who can execute the contract migration
       * </pre>
       *
       * <code>string admin = 3 [(.gogoproto.moretags) = "yaml:&#92;"admin&#92;""];</code>
       * @param value The admin to set.
       * @return This builder for chaining.
       */
      public Builder setAdmin(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        admin_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Admin is who can execute the contract migration
       * </pre>
       *
       * <code>string admin = 3 [(.gogoproto.moretags) = "yaml:&#92;"admin&#92;""];</code>
       * @return This builder for chaining.
       */
      public Builder clearAdmin() {
        admin_ = getDefaultInstance().getAdmin();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Admin is who can execute the contract migration
       * </pre>
       *
       * <code>string admin = 3 [(.gogoproto.moretags) = "yaml:&#92;"admin&#92;""];</code>
       * @param value The bytes for admin to set.
       * @return This builder for chaining.
       */
      public Builder setAdminBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        admin_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private long codeId_ ;
      /**
       * <pre>
       * CodeID is the reference to the stored Wasm code
       * </pre>
       *
       * <code>uint64 code_id = 4 [(.gogoproto.customname) = "CodeID", (.gogoproto.moretags) = "yaml:&#92;"code_id&#92;""];</code>
       * @return The codeId.
       */
      @java.lang.Override
      public long getCodeId() {
        return codeId_;
      }
      /**
       * <pre>
       * CodeID is the reference to the stored Wasm code
       * </pre>
       *
       * <code>uint64 code_id = 4 [(.gogoproto.customname) = "CodeID", (.gogoproto.moretags) = "yaml:&#92;"code_id&#92;""];</code>
       * @param value The codeId to set.
       * @return This builder for chaining.
       */
      public Builder setCodeId(long value) {
        
        codeId_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * CodeID is the reference to the stored Wasm code
       * </pre>
       *
       * <code>uint64 code_id = 4 [(.gogoproto.customname) = "CodeID", (.gogoproto.moretags) = "yaml:&#92;"code_id&#92;""];</code>
       * @return This builder for chaining.
       */
      public Builder clearCodeId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        codeId_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString initMsg_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * InitMsg is the raw message used when instantiating a contract
       * </pre>
       *
       * <code>bytes init_msg = 5 [(.gogoproto.moretags) = "yaml:&#92;"init_msg&#92;"", (.gogoproto.casttype) = "encoding/json.RawMessage"];</code>
       * @return The initMsg.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getInitMsg() {
        return initMsg_;
      }
      /**
       * <pre>
       * InitMsg is the raw message used when instantiating a contract
       * </pre>
       *
       * <code>bytes init_msg = 5 [(.gogoproto.moretags) = "yaml:&#92;"init_msg&#92;"", (.gogoproto.casttype) = "encoding/json.RawMessage"];</code>
       * @param value The initMsg to set.
       * @return This builder for chaining.
       */
      public Builder setInitMsg(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        initMsg_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * InitMsg is the raw message used when instantiating a contract
       * </pre>
       *
       * <code>bytes init_msg = 5 [(.gogoproto.moretags) = "yaml:&#92;"init_msg&#92;"", (.gogoproto.casttype) = "encoding/json.RawMessage"];</code>
       * @return This builder for chaining.
       */
      public Builder clearInitMsg() {
        bitField0_ = (bitField0_ & ~0x00000010);
        initMsg_ = getDefaultInstance().getInitMsg();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:terra.wasm.v1beta1.ContractInfo)
    }

    // @@protoc_insertion_point(class_scope:terra.wasm.v1beta1.ContractInfo)
    private static final terra.wasm.v1beta1.Wasm.ContractInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new terra.wasm.v1beta1.Wasm.ContractInfo();
    }

    public static terra.wasm.v1beta1.Wasm.ContractInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ContractInfo>
        PARSER = new com.google.protobuf.AbstractParser<ContractInfo>() {
      @java.lang.Override
      public ContractInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ContractInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ContractInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public terra.wasm.v1beta1.Wasm.ContractInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_terra_wasm_v1beta1_Params_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_terra_wasm_v1beta1_Params_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_terra_wasm_v1beta1_CodeInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_terra_wasm_v1beta1_CodeInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_terra_wasm_v1beta1_ContractInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_terra_wasm_v1beta1_ContractInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035terra/wasm/v1beta1/wasm.proto\022\022terra.w" +
      "asm.v1beta1\032\024gogoproto/gogo.proto\"\303\001\n\006Pa" +
      "rams\0227\n\021max_contract_size\030\001 \001(\004B\034\362\336\037\030yam" +
      "l:\"max_contract_size\"\0225\n\020max_contract_ga" +
      "s\030\002 \001(\004B\033\362\336\037\027yaml:\"max_contract_gas\"\022?\n\025" +
      "max_contract_msg_size\030\003 \001(\004B \362\336\037\034yaml:\"m" +
      "ax_contract_msg_size\":\010\350\240\037\001\230\240\037\000\"\207\001\n\010Code" +
      "Info\022-\n\007code_id\030\001 \001(\004B\034\362\336\037\016yaml:\"code_id" +
      "\"\342\336\037\006CodeID\022\'\n\tcode_hash\030\002 \001(\014B\024\362\336\037\020yaml" +
      ":\"code_hash\"\022#\n\007creator\030\003 \001(\tB\022\362\336\037\016yaml:" +
      "\"creator\"\"\361\001\n\014ContractInfo\022#\n\007address\030\001 " +
      "\001(\tB\022\362\336\037\016yaml:\"address\"\022#\n\007creator\030\002 \001(\t" +
      "B\022\362\336\037\016yaml:\"creator\"\022\037\n\005admin\030\003 \001(\tB\020\362\336\037" +
      "\014yaml:\"admin\"\022-\n\007code_id\030\004 \001(\004B\034\362\336\037\016yaml" +
      ":\"code_id\"\342\336\037\006CodeID\022A\n\010init_msg\030\005 \001(\014B/" +
      "\362\336\037\017yaml:\"init_msg\"\372\336\037\030encoding/json.Raw" +
      "Message:\004\350\240\037\001B,Z*github.com/classic-terr" +
      "a/core/x/wasm/typesb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.GoGoProtos.getDescriptor(),
        });
    internal_static_terra_wasm_v1beta1_Params_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_terra_wasm_v1beta1_Params_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_terra_wasm_v1beta1_Params_descriptor,
        new java.lang.String[] { "MaxContractSize", "MaxContractGas", "MaxContractMsgSize", });
    internal_static_terra_wasm_v1beta1_CodeInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_terra_wasm_v1beta1_CodeInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_terra_wasm_v1beta1_CodeInfo_descriptor,
        new java.lang.String[] { "CodeId", "CodeHash", "Creator", });
    internal_static_terra_wasm_v1beta1_ContractInfo_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_terra_wasm_v1beta1_ContractInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_terra_wasm_v1beta1_ContractInfo_descriptor,
        new java.lang.String[] { "Address", "Creator", "Admin", "CodeId", "InitMsg", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.protobuf.GoGoProtos.casttype);
    registry.add(com.google.protobuf.GoGoProtos.customname);
    registry.add(com.google.protobuf.GoGoProtos.equal);
    registry.add(com.google.protobuf.GoGoProtos.goprotoStringer);
    registry.add(com.google.protobuf.GoGoProtos.moretags);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.protobuf.GoGoProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
